services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./infra/postgres/init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  user-service:
    build: ./backend/demo/
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/user_db
      DB_USERNAME: admin
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8001
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8001:8001"
    networks:
      - app-network

  project-service:
    build: ./backend/project-service/
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/core_db
      DB_USERNAME: admin
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8002
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8002:8002"
    networks:
      - app-network

  gateway:
    build: ./backend/gateway/
    depends_on:
      user-service:
        condition: service_started
      project-service:
        condition: service_started
    environment:
      SERVER_PORT: 8080
      USER_SERVICE_URL: http://user-service:8001
      PROJECT_SERVICE_URL: http://project-service:8002
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data: