spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8000}
          predicates:
            - Path=/api/auth/**,/api/users/**
          filters:
            - StripPrefix=1

        - id: project-service
          uri: ${PROJECT_SERVICE_URL:http://localhost:8002}
          predicates:
            - Path=/api/project/**,/api/task/**
          filters:
            - StripPrefix=1

server:
  port: ${SERVER_PORT:8080}
